### ISSUE TITLE
[REQUEST] KBackup for Minecraft 1.17.1 version

### ISSUE THREAD

**Issue by Dream4Leo** [keuin/KBackup-Fabric#4]
I am currently hosting a 1.17.1 fabric server and seeking for incremental backup mods. After reading your introduction I think I find the perfect one. Much appreciation if you can compile an 1.17.1 version or provide compiling instructions.

**Comment by keuin** [comment]
不同版本的MC需要编译不同的jar文件，是因为fabric api和yarn在不同MC版本所提供的类名、方法名可能有变，而适配新版MC只需要修改mod代码中这些变动的部分。你可以用IDEA打开`1.16.4`分支的代码，从[这里](https://fabricmc.net/versions.html)复制`gradle.properties`对应的配置项来更新项目代码里的这个文件。然后，点击IDE内置的Gradle面板的“build”命令来打包获得jar。

这段时间有点忙，不过这月有空的话我会去适配1.17.1版本的Minecraft。

**Comment by Dream4Leo** [comment]
谢谢！

**Comment by keuin** [comment]
[Version 1.6.7](https://github.com/keuin/KBackup-Fabric/releases/tag/v1.6.7) now supports Minecraft 1.17.1.
